### ISSUE TITLE
Review docs skeleton

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-query-logic#6]
Steps:

1. checkout `5-0` branch of canjs: https://github.com/canjs/canjs/tree/5-0 
2. `npm install && ./node_modules/.bin/bit-docs`
3.  Launch local fileserver
4.  Open: http://localhost:8080/canjs/doc/can-query-logic.html

You should see:

![canjs_-_can-query-logic](https://user-images.githubusercontent.com/78602/38374471-5562e2e8-38b9-11e8-97c3-dcf00c10e443.png)

Please review that page for understandability, clarity, correctness.  Do these APIs make sense?  Are they explained well?

> NOTE A: There's going to be a "Using queryLogic instances" section.  I'm focused on the different configuration options right now.

> NOTE B: The methods are not documented yet.  That will happen later.

**Comment by phillipskevin** [comment]
> By default, filter properties like `status` in `{filter: {status: "complete"}}` are hydrated to one of the [can-query/types/comparisons comparison types] like GreaterThan.

I was confused by this sentence. Is it saying that an instance of `GreaterThan` is created and then hydrated with the data `{ status: "complete" }`? I think using the term "hydrated" here might make this confusing for people.

**Comment by phillipskevin** [comment]
![image](https://user-images.githubusercontent.com/5851984/38379173-8511e8ca-38c5-11e8-9730-8dc17dcf3a0c.png)

Are you calling this parameter `options` so that later it could be used for things other than translating parameters?

The name `options` seems generic for what the docs currently say it's for.

**Comment by phillipskevin** [comment]
Can we link to the _Special Comparison Logic_ section? I wanted to jump to it.

![image](https://user-images.githubusercontent.com/5851984/38379397-2f1021f2-38c6-11e8-8723-be9b11f6a86e.png)

**Comment by phillipskevin** [comment]
I stumbled over reading this:

> Those values [can-deparam](http://localhost/canjs/doc/can-deparam.html)-ed into a query object look like this:

Maybe it should say

> Those values [deserialized](http://localhost/canjs/doc/can-deparam.html) into a query object look like this:

**Comment by phillipskevin** [comment]
This paragraph doesn't seem related to what is above it:

![image](https://user-images.githubusercontent.com/5851984/38379730-40a85eba-38c7-11e8-82d0-4fbef4289717.png)

**Comment by phillipskevin** [comment]
When you first showed `QueryLogic.prototype.union`:

```js
todoLogic.union(
    {filter: {status: ["new","assigned"] }},
    {filter: {status: "complete" }}
) //-> {}
```

I expected a third argument with an array of members to match what you showed previously with `filterMembers`.

I realize now that this would be `unionMembers`, but maybe this needs a comment or additional explanation about how you can compare sets directly without needed to create any `Todo`s.

**Comment by phillipskevin** [comment]
This example is great. I think it would be useful to add comments to the other possible cases:

![image](https://user-images.githubusercontent.com/5851984/38381042-370b01ec-38cb-11e8-8d9b-9fce69efe783.png)

**Comment by phillipskevin** [comment]
I've added review comments about this to https://docs.google.com/document/d/1dOUtk5nJruJiEiHmyweWy3g9h-8ZogFJhVPDXnRuHOM/edit?usp=sharing.
